### PR TITLE
Add dbhost to wp-config create function

### LINKED ISSUE #431: Error with Remote MySQL: no dbhost passed to wp-cli when creating config
In version 3+ when creating a new site we get an error like so:
Unable to move file from /var/www/testsite222.com/htdocs/wp-config.php to /var/www/testsite222.com

From testing on our beta box it looks to be a problem with site_functions.py - setupwordpress 
the dbhost for our remote server is not supplied and we do not have mysql running on localhost. This causes wp-cli to throw an error and no config file is created. 

This in turn causes the unable to move error.

Thanks,
Josh

### PR DESCRIPTION
**Pull request by joshlyford**
Fix #431

### CODE REVIEW

**Comment by harshadyeola** [comment]
@joshlyford 
Thanks for pointing out this issue 
You have made right changes, but i guess you have messed something with multisite config.
I guess you should review your pull request.
We are getting this issue
```bash
$ sudo ee site create site5.net --wpsubdir

Setting up NGINX configuration [Done]

Setting up webroot [Done]

Downloading Wordpress [Done]

Setting up database [Done]

tuple index out of range
```
https://travis-ci.org/rtCamp/easyengine/builds/51121678

**Comment by joshlyford** [comment]
Good catch. I see the problem and will update the pull request in a bit.

**Comment by joshlyford** [comment]
@harshadyeola should now be fixed. please let me know if not.

**Comment by MiteshShah** [comment]
@joshlyford You can check Travis status for pull request at
https://travis-ci.org/rtCamp/easyengine/pull_requests

**Pull request merged**
